name       : copyq
version    : 3.11.1
release    : 5
source     :
    - https://github.com/hluk/CopyQ/archive/v3.11.1.tar.gz : a0b0a7d90aa67a48b4ab94b23bfa16da5602de80ef82862451bac619ede3d4bb
homepage   : https://hluk.github.io/CopyQ/
license    : GPL-3.0-or-later
component  : system.utils
summary    : Clipboard manager with advanced features
description: |
    CopyQ is advanced clipboard manager with editing and scripting features. CopyQ monitors system clipboard and saves its content in customized tabs. Saved clipboard can be later copied and pasted directly into any application.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
