name       : copyq
version    : 3.8.0
release    : 1
source     :
    - https://github.com/hluk/CopyQ/archive/v3.8.0.tar.gz : 57ecda358937347fbcdec20b49f0c22ad36a5c502cab4df5467e276e0e2bb751
license    : GPL-3.0-or-later
component  : system.utils
summary    : Clipboard manager with advanced features
description: |
    CopyQ is advanced clipboard manager with editing and scripting features.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
