name       : copyq
version    : 7.1.0
release    : 16
source     :
    - https://github.com/hluk/CopyQ/archive/refs/tags/v7.1.0.tar.gz : ce0265b0a86350fda7bfa1a9d4b74d794a4077551b28186012683567d6fd8158
homepage   : https://hluk.github.io/CopyQ/
license    : GPL-3.0-or-later
component  : system.utils
summary    : Clipboard manager with advanced features
description: |
    CopyQ is advanced clipboard manager with editing and scripting features. CopyQ monitors system clipboard and saves its content in customized tabs. Saved clipboard can be later copied and pasted directly into any application.
builddeps  :
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6UiTools)
    - pkgconfig(Qt6WaylandCompositor)
    - pkgconfig(Qt6Core)
    - pkgconfig(xtst)
    - pkgconfig(wayland-scanner)
    - extra-cmake-modules
    - knotifications-devel
setup      : |
    %cmake_ninja \
        -DWITH_QT6:BOOL=ON \
        -DQtWaylandScanner_EXECUTABLE:FILEPATH=/usr/lib64/qt6/qtwaylandscanner
build      : |
    %ninja_build
install    : |
    %ninja_install
