name       : copyq
version    : 3.9.2
release    : 2
source     :
    - https://github.com/hluk/CopyQ/archive/v3.9.2.tar.gz : 8d526c7b0ab7a2e5ae91ef68df104277217c6679b15a0f100ae2de50247c993b
license    : GPL-3.0-or-later
component  : system.utils
summary    : Clipboard manager with advanced features
description: |
    CopyQ is advanced clipboard manager with editing and scripting features. CopyQ monitors system clipboard and saves its content in customized tabs. Saved clipboard can be later copied and pasted directly into any application.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
