name       : copyq
version    : 6.1.0
release    : 12
source     :
    - https://github.com/hluk/CopyQ/archive/refs/tags/v6.1.0.tar.gz : d235b31224264e7fa463020f1a934143aa287a4d9cb9bbb6883563ad66e84099
homepage   : https://hluk.github.io/CopyQ/
license    : GPL-3.0-or-later
component  : system.utils
summary    : Clipboard manager with advanced features
description: |
    CopyQ is advanced clipboard manager with editing and scripting features. CopyQ monitors system clipboard and saves its content in customized tabs. Saved clipboard can be later copied and pasted directly into any application.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WaylandCompositor)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - pkgconfig(wayland-scanner)
    - extra-cmake-modules
    - knotifications-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
