name       : copyq
version    : 6.3.2
release    : 14
source     :
    - https://github.com/hluk/CopyQ/archive/refs/tags/v6.3.2.tar.gz : ce122ed7f8e3e230b1c6dcce8f1ec6d717eef8c59829390cae1750c35b342c4a
homepage   : https://hluk.github.io/CopyQ/
license    : GPL-3.0-or-later
component  : system.utils
summary    : Clipboard manager with advanced features
description: |
    CopyQ is advanced clipboard manager with editing and scripting features. CopyQ monitors system clipboard and saves its content in customized tabs. Saved clipboard can be later copied and pasted directly into any application.
builddeps  :
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6UiTools)
    - pkgconfig(Qt6WaylandCompositor)
    - pkgconfig(Qt6Core)
    - pkgconfig(xtst)
    - pkgconfig(wayland-scanner)
    - extra-cmake-modules
    - knotifications-devel
setup      : |
    %cmake_ninja \
        -DWITH_QT6:BOOL=ON \
        -DQtWaylandScanner_EXECUTABLE:FILEPATH=/usr/lib64/qt6/qtwaylandscanner
build      : |
    %ninja_build
install    : |
    %ninja_install
