name       : copyq
version    : 5.0.0
release    : 10
source     :
    - https://github.com/hluk/CopyQ/archive/refs/tags/v5.0.0.tar.gz : cc77ef8104771bbaa8f99025c1e7a3d318892b0e8767021f3243457b0c68948e
homepage   : https://hluk.github.io/CopyQ/
license    : GPL-3.0-or-later
component  : system.utils
summary    : Clipboard manager with advanced features
description: |
    CopyQ is advanced clipboard manager with editing and scripting features. CopyQ monitors system clipboard and saves its content in customized tabs. Saved clipboard can be later copied and pasted directly into any application.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WaylandCompositor)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - pkgconfig(wayland-scanner)
    - extra-cmake-modules
    - knotifications-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
