name       : copyq
version    : 6.0.1
release    : 11
source     :
    - https://github.com/hluk/CopyQ/archive/refs/tags/v6.0.1.tar.gz : 8d0b0fa840993fa100e888a5a1098e2769e3c234cd44236d75039e5c6e517645
homepage   : https://hluk.github.io/CopyQ/
license    : GPL-3.0-or-later
component  : system.utils
summary    : Clipboard manager with advanced features
description: |
    CopyQ is advanced clipboard manager with editing and scripting features. CopyQ monitors system clipboard and saves its content in customized tabs. Saved clipboard can be later copied and pasted directly into any application.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WaylandCompositor)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - pkgconfig(wayland-scanner)
    - extra-cmake-modules
    - knotifications-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
